-- 스키마의 유일한 기준 (docs/design/03-domain-model.md §2~§5 · §7)
-- 기동마다 실행된다. IF NOT EXISTS라 재기동해도 기존 테이블과 데이터는 그대로 남는다
-- 테이블을 바꿨으면 로컬 DB는 `docker compose down -v` 후 다시 올린다

CREATE TABLE IF NOT EXISTS tenant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code       VARCHAR(100) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_tenant PRIMARY KEY (id),
    CONSTRAINT uk_tenant_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id    BIGINT       NOT NULL,
    product_code VARCHAR(100) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT fk_product_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT uk_product_tenant_code UNIQUE (tenant_id, product_code)
);

CREATE TABLE IF NOT EXISTS inventory (
    product_id BIGINT      NOT NULL,
    quantity   BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_inventory PRIMARY KEY (product_id),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT ck_inventory_quantity_non_negative CHECK (quantity >= 0)
);
